version: "3.9"
services:
  postgres_cluster:
    image: postgres:16
    container_name: postgres-cluster
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      # This folder is scanned by Postgres only on the very first boot
      - ./infrastructure/postgres:/docker-entrypoint-initdb.d/
      # Persistence: your data stays even if you stop containers
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  gateway:
    image: ed18c/gateway-service:2781336
    container_name: gateway
    ports:
      - "3000:3000"
    environment:
      USER_SERVICE_URL: http://user-service:3001
      RESOURCES_SERVICE_URL: http://resource-service:3002
      OPERATION_SERVICE_URL: http://operation-service:3003
      GATEWAY_PORT: 3000
    depends_on:
      user-service:
        condition: service_started
      resource-service:
        condition: service_started
      operation-service:
        condition: service_started

  user-service:
    image: ed18c/user-service:2781336
    container_name: user-service
    ports:
      - "3001:3001"
    environment:
      JWT_SECRET: your_jwt_secret_key
      REFRESH_JWT_SECRET: your_refresh_token_secret_key
      AUTH_DATABASE_URL: postgres://postgres:postgres@postgres_cluster:5432/auth_db
      AUTH_PORT: 3001
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672
    depends_on:
      postgres_cluster:
        condition: service_healthy
      rabbitmq:
        condition: service_started
  resource-service:
    image: ed18c/resource-service:2781336
    container_name: resource-service
    ports:
      - "3002:3002"
    environment:
      JWT_SECRET: your_jwt_secret_key
      REFRESH_JWT_SECRET: your_refresh_token_secret_key
      RESOURCE_DATABASE_URL: postgres://postgres:postgres@postgres_cluster:5432/resource_db
      RESOURCE_PORT: 3002
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672
    depends_on:
      postgres_cluster:
        condition: service_healthy
      rabbitmq:
        condition: service_started
  operation-service:
    image: ed18c/operation-service:2781336
    container_name: operation-service
    ports:
      - "3003:3003"
    environment:
      JWT_SECRET: your_jwt_secret_key
      REFRESH_JWT_SECRET: your_refresh_token_secret_key
      OPERATION_DATABASE_URL: postgres://postgres:postgres@postgres_cluster:5432/operation_db
      OPERATION_PORT: 3003
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672
      RESOURCE_SERVICE_URL: http://resource-service:3002
    depends_on:
      postgres_cluster:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      resource-service:
        condition: service_started


volumes:
  postgres_data: