version: "3.9"
services:
  analytics-db:
    image: postgres:16
    container_name: relay-analytics-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: analytics_db
    ports:
      - "5438:5432"
    volumes:
      - ./sql/transaction_init.sql:/docker-entrypoint-initdb.d/init.sql

  messaging_db:
    image: postgres:16
    container_name: messaging-mvc-prisma-db
    environment:
      POSTGRES_USER: messaging_user
      POSTGRES_PASSWORD: messaging_password
      POSTGRES_DB: messaging_db
    ports:
      - "5437:5432"
    volumes:
      - ./sql/messaging_init.sql:/docker-entrypoint-initdb.d/init.sql
  notification_db:
    image: postgres:16
    container_name: notification-mvc-prisma-db
    environment:
      POSTGRES_USER: notification_user
      POSTGRES_PASSWORD: notification_password
      POSTGRES_DB: notification_db
    ports:
      - "5436:5432"
    volumes:
      - ./sql/notification_init.sql:/docker-entrypoint-initdb.d/init.sql
  auth_db:
    image: postgres:16
    container_name: auth-mvc-prisma-db
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
  resource_db:
    image: postgres:16
    container_name: resource-mvc-prisma-db
    environment:
      POSTGRES_USER: resource_user
      POSTGRES_PASSWORD: resource_password
      POSTGRES_DB: resource_db
    ports:
      - "5433:5432"
    volumes:
      - ./sql/resource_init.sql:/docker-entrypoint-initdb.d/init.sql
  transaction_db:
    image: postgres:16
    container_name: transaction-mvc-prisma-db
    environment:
      POSTGRES_USER: transaction_user
      POSTGRES_PASSWORD: transaction_password
      POSTGRES_DB: transaction_db
    ports:
      - "5434:5432"
    volumes:
      - ./sql/transaction_init.sql:/docker-entrypoint-initdb.d/init.sql
  review-reputation_db:
    image: postgres:16
    container_name: review-reputation-mvc-prisma-db
    environment:
      POSTGRES_USER: review_user
      POSTGRES_PASSWORD: review_password
      POSTGRES_DB: review_db
    ports:
      - "5435:5432"
    volumes:
      - ./sql/review_init.sql:/docker-entrypoint-initdb.d/init.sql
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
