version: "3.9"

services:
  auth_db:
    image: postgres:16
    container_name: auth-mvc-prisma-db
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  resource_db:
    image: postgres:16
    container_name: resource-mvc-prisma-db
    environment:
      POSTGRES_USER: resource_user
      POSTGRES_PASSWORD: resource_password
      POSTGRES_DB: resource_db
    ports:
      - "5433:5432"
    volumes:
      - ./sql/resource_init.sql:/docker-entrypoint-initdb.d/init.sql

  transaction_db:
    image: postgres:16
    container_name: transaction-mvc-prisma-db
    environment:
      POSTGRES_USER: transaction_user
      POSTGRES_PASSWORD: transaction_password
      POSTGRES_DB: transaction_db
    ports:
      - "5434:5432"
    volumes:
      - ./sql/transaction_init.sql:/docker-entrypoint-initdb.d/init.sql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  # Auth service
  auth-service:
    build: ./ed18c/user-service
    env_file: ./ed18c/user-service/.env
    depends_on:
      - auth_db
      - rabbitmq
    ports:
      - "3001:3001"

  # Resource service
  resource-service:
    build: ./ed18c/resource-service
    env_file: ./ed18c/resource-service/.env
    depends_on:
      - resource_db
      - rabbitmq
    ports:
      - "3002:3002"

  # Transaction service
  transaction-service:
    build: ./ed18c/transaction-service
    env_file: ./ed18c/transaction-service/.env
    depends_on:
      - transaction_db
      - rabbitmq
    ports:
      - "3003:3003"

  # Gateway service
  gateway-service:
    build: ./ed18c/gateway-service
    env_file: ./ed18c/gateway-service/.env
    depends_on:
      - auth-service
      - resource-service
      - transaction-service
    ports:
      - "3000:3000"
