apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: relay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: ed18c/gateway-service:8d06298
          ports:
            - containerPort: 3000
          env:
            - name: GATEWAY_PORT
              value: "3000"
            - name: USER_SERVICE_URL
              value: "http://user-service:3001"
            - name: RESOURCES_SERVICE_URL
              value: "http://resource-service:3002"
            - name: OPERATION_SERVICE_URL
              value: "http://operation-service:3003"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: relay
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 80 # We use port 80 for the service to make it web-standard
      targetPort: 3000
  type: ClusterIP