apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: relay
data:
  GATEWAY_PORT: "3000"
  JWT_SECRET: "7f94eae1d04e72564ac2b4cabbd7dfde45ac28be4855902cd77a8dbfebffe6c63532b1330040d52497af9a50db6c58fca59975c4dbde0a63bcb21c9bbb411bfb"
  RESOURCES_SERVICE_URL: "http://resource-service:3002"
  TRANSACTION_SERVICE_URL: "http://transaction-service:3003"
  USER_SERVICE_URL: "http://auth-service:3001"