apiVersion: v1
kind: Secret
metadata:
  name: jwt-secrets
  namespace: relay
type: Opaque
data:
  ACCESS_TOKEN_SECRET: 7f94eae1d04e72564ac2b4cabbd7dfde45ac28be4855902cd77a8dbfebffe6c63532b1330040d52497af9a50db6c58fca59975c4dbde0a63bcb21c9bbb411bfb
  REFRESH_TOKEN_SECRET: b328a950b5286a94999124c4ebe1ca02b935914b8152b2c75d22ae7f1c71743971ae42e0cadf133bbd0d3381b9d79b1b329fa1ee42a6c4036f0de6edf259a421