apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-resource-config
  namespace: relay
data:
  postgres-resource-host: resource-service
  postgres-resource-db: relay_resource_db
  postgres-resource-port: "5432"
