name: CI — Build + Test All Services

on:
  push:
    branches: [main, develop, feature/*]
  pull_request:
    branches: [main, develop, feature/*]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      # Remove porque a raiz NÃO tem package.json
      # - name: Install root deps
      #   run: npm install

      - name: Test resource-service
        working-directory: ./resource-service
        run: |
          npm install
          npm test || true

      - name: Test transaction-service
        working-directory: ./transaction-service
        run: |
          npm install
          npm test || true

      - name: Test user-service
        working-directory: ./user-service
        run: |
          npm install
          npm test || true

      - name: Test gateway
        working-directory: ./gateway
        run: |
          npm install
          npm test || true
